#!/usr/bin/env sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)

export RUNTIME_DOCKER_HOST_ROOT="${RUNTIME_DOCKER_HOST_ROOT:-$REPO_ROOT}"
export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-grin-runtime}"

cd "$REPO_ROOT"

docker compose down
rm -f controller/runtime.db
rm -rf nodes/node-1 nodes/node-2 nodes/grinpp-node-1
printf '# Generated by Runtime Controller. Do not edit by hand.\nservices: {}\n' > compose/docker-compose.nodes.generated.yml
docker compose up -d --build

