apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: Runtime Controller
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: http://runtime-controller:8080
    jsonData:
      auth_method: none
