from __future__ import annotations

from .utils import COMPOSE_DIR, write_text_if_changed


HEADER = "# Generated by Runtime Controller. Do not edit by hand.\n"


def service_name(node: dict) -> str:
    return node["container_name"]


def render_node_service(node: dict) -> str:
    name = service_name(node)
    rel_path = node["node_path"].replace("\\", "/")
    labels = {
        "grin.node_id": node["node_id"],
        "grin.node_name": node["node_name"],
        "grin.node_type": node["node_type"],
        "grin.profile": node["profile"],
        "grin.experiment_id": node.get("experiment_id") or "",
        "grin.image_tag": node.get("image_tag") or "",
        "grin.commit_hash": node.get("git_commit_hash") or "",
    }
    label_lines = "\n".join(f'      - "{key}={value}"' for key, value in labels.items())
    if node["node_type"] == "grinpp":
        image = f'{node["docker_image"]}:{node["image_tag"]}'
        command = '["--public-node-api", "--floonet"]'
        volume_target = "/root/.GrinPP"
    else:
        image = f'{node["docker_image"]}:{node["image_tag"]}'
        command = '["--testnet", "server", "-c", "/root/.grin/test/grin-server.toml", "run"]'
        volume_target = "/root/.grin/test"
    return f"""  {name}:
    image: {image}
    container_name: {name}
    depends_on:
      - grin-gw
    command: {command}
    volumes:
      - ${{RUNTIME_DOCKER_HOST_ROOT:-..}}/{rel_path}:{volume_target}
    labels:
{label_lines}
    networks:
      cluster:
        aliases:
          - {name}
"""


def render_compose(nodes: list[dict]) -> str:
    active = [node for node in nodes if node["node_type"] != "gateway" and node["status"] != "deleted"]
    body = "".join(render_node_service(node) for node in active)
    if not body:
        return HEADER + "services: {}\n"
    return HEADER + "services:\n" + body


def generate(nodes: list[dict]) -> None:
    write_text_if_changed(COMPOSE_DIR / "docker-compose.nodes.generated.yml", render_compose(nodes))
